/**
 * Bakes the ODOT camera catalog into data/cameras.json at build time.
 *
 * Why build time: the OHGO API needs a key, and a key in a static page is a
 * published key. Camera locations change on the order of months, so fetching
 * them nightly in CI and committing the result keeps the site fully static —
 * no serverless functions, nothing to pay for, no key in the browser.
 *
 * The image URLs it writes are keyless and public, which is why the site can
 * still show live imagery with no backend at all.
 *
 * Usage:  OHGO_API_KEY=... node scripts/fetch-cameras.mjs
 * Without a key it exits 0 and leaves the existing catalog alone.
 */

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "data", "cameras.json");

const KEY = process.env.OHGO_API_KEY;
const LAT = Number(process.env.OHGO_LAT ?? 40.3871);
const LON = Number(process.env.OHGO_LON ?? -80.6348);
const MILES = Number(process.env.OHGO_RADIUS_MILES ?? 25);

if (!KEY) {
  console.log(
    "OHGO_API_KEY not set — keeping the existing catalog.\n" +
      "Get a free key at https://publicapi.ohgo.com/ and add it as a repo secret to enable this."
  );
  process.exit(0);
}

/** OHGO returns PascalCase; the frontend speaks camelCase. Normalise here, once. */
function normalise(result) {
  return {
    id: result.Id,
    latitude: result.Latitude,
    longitude: result.Longitude,
    location: result.Location,
    description: result.Description,
    views: (result.CameraViews ?? [])
      .filter((v) => v.SmallUrl || v.LargeUrl)
      .map((v) => ({
        direction: v.Direction,
        mainRoute: v.MainRoute,
        smallUrl: v.SmallUrl,
        largeUrl: v.LargeUrl ?? v.SmallUrl,
      })),
  };
}

async function main() {
  const url = new URL("https://publicapi.ohgo.com/api/v1/cameras");
  url.searchParams.set("radius", `${LAT},${LON},${MILES}`);
  url.searchParams.set("page-all", "true");

  console.log(`fetching cameras within ${MILES} mi of ${LAT}, ${LON}…`);

  const res = await fetch(url, { headers: { Authorization: `APIKEY ${KEY}` } });
  if (!res.ok) {
    throw new Error(`OHGO responded ${res.status} ${res.statusText}: ${await res.text()}`);
  }

  const body = await res.json();
  const cameras = (body.Results ?? []).map(normalise).filter((c) => c.views.length > 0);

  if (cameras.length === 0) {
    // Never let a quiet API response blank out a working catalog.
    console.warn("OHGO returned no cameras — leaving the existing catalog in place.");
    process.exit(0);
  }

  const next = {
    source: "ohgo",
    generatedAt: new Date().toISOString(),
    center: { lat: LAT, lon: LON },
    radiusMiles: MILES,
    note: "Generated by scripts/fetch-cameras.mjs. Image URLs are keyless and public.",
    cameras: cameras.sort((a, b) => String(a.location).localeCompare(String(b.location))),
  };

  // Skip no-op commits: compare everything except the timestamp.
  const stable = (o) => JSON.stringify({ ...o, generatedAt: null });
  const prev = await readFile(OUT, "utf8").then(JSON.parse).catch(() => null);
  if (prev && stable(prev) === stable(next)) {
    console.log(`no change — ${cameras.length} cameras, catalog already current.`);
    process.exit(0);
  }

  await writeFile(OUT, JSON.stringify(next, null, 2) + "\n");
  const views = cameras.reduce((n, c) => n + c.views.length, 0);
  console.log(`wrote ${cameras.length} cameras (${views} views) to data/cameras.json`);
}

main().catch((err) => {
  console.error("catalog update failed:", err.message);
  process.exit(1);
});
